### ISSUE TITLE
commentstring doesn't seem to take affect with setlocal

### ISSUE THREAD

**Issue by perryao** [tsandall/vim-rego#2]
If I use `set` instead of `setlocal` then the comment string is `#` as expected. Otherwise it's still `/* */`. Any thoughts?

**Comment by tsandall** [comment]
@perryao I am not vim plugin expert. I'm not sure. Any thoughts @multani ?

**Comment by multani** [comment]
I'm not a vim script expert either, but all the ftplugin plugins I've met in the wild were using `setlocal` instead of `set`.
@perryao How do you comment your code to get these `/* */` markers actually?

**Comment by multani** [comment]
For reference: [Vim's `comments` configuration in the Vim repository](https://github.com/search?utf8=%E2%9C%93&q=comments+repo%3Avim%2Fvim+path%3A%2Fruntime%2Fftplugin&type=Code&ref=advsearch&l=&l=)

**Comment by perryao** [comment]
yep definitely looks like this is the preferred approach. I'm going to assume I have a conflict somewhere. Feel free to close this. I'll post back here if I find the conflict.
