### ISSUE TITLE
comments and commentstring settings should be prefixed by autocmds as well

### ISSUE THREAD

**Issue by bzp99** [tsandall/vim-rego#7]
In `ftdetect/rego.vim`,

    setlocal comments=b:#,fb:-
    setlocal commentstring=#\ %s

Should actually be

    autocmd FileType rego setlocal comments=b:#,fb:-
    autocmd FileType rego setlocal commentstring=#\ %s

See also https://github.com/sheerun/vim-polyglot/issues/486

**Comment by tsandall** [comment]
@bzp99 I've converted to the church of Emacs. If you'd like to submit a PR, please feel free!

**Comment by bzp99** [comment]
I am on it!
